### ISSUE TITLE
Stock control

### ISSUE THREAD

**Issue by mikaelbirkelundjohansen** [discimport/discimport-build#12]
Better stock handling so it is easier to edit and see the different variations on stock. There should be search functions and sort functions. This list / lists should also easily could be used by the end of the year to see how much is actually in stock.

**Comment by lsolesen** [comment]
I've done a bit of work in http://github.com/discimport/discimport_stock. Still a lot of room for improvement.

**Comment by lsolesen** [comment]
Closing this for now, as we got a better control now. Please reopen if it is not sufficient to make the stock on each product better.
