### ISSUE TITLE
All taxonomy menu items goes to discgolf

### ISSUE THREAD

**Issue by lsolesen** [discimport/discimport-build#21]
@mikaelbirkelundjohansen Looking at this now.

**Comment by lsolesen** [comment]
This must have happened after the most recent Commerce Kickstart Release update. Mind taking a look at this @mglaman

**Comment by lsolesen** [comment]
@mglaman answered in an e-mail:

The issue is the category field reset the vocabulary it points to. What's the proper vocabulary name? I have a snippet used to fix a few sites.

Also, CK2 now supports Features Override (verified in upgrade tests) so that should be one thing enabled (provided now) and utilized to prevent this.

**Comment by lsolesen** [comment]
@mglaman It is the taxonomy 'colllection' which is utilized in the menu. That is the default one used in CK2?

**Comment by mglaman** [comment]
```
  $field = field_info_field('field_product_category');
  $field['settings']['allowed_values'][0]['vocabulary'] = 'product_category';
  field_update_field($field);
```

This is the code snippet to reset the vocabulary if it has changed. It is "collection" if demo store, "product_category" if not demo store.

**Comment by lsolesen** [comment]
@mglaman Does this just go into an update hook?

**Comment by lsolesen** [comment]
@mikaelbirkelundjohansen Temporary, I've substituted the links with product search links. This should still be fixed though.

**Comment by mglaman** [comment]
@lsolesen it would go in an update hook, but that shouldn't run (I don't think) as commerce_kickstart_demo_store returns true. What was the old link, for testing purposes

**Comment by mglaman** [comment]
@lsolesen so I ran "drush en discimport_deploy -y" (since it isn't enabled) and an update hook I added to reset taxonomy_menu fixed up the catalog -- discimport/discimport_deploy@c514b2e4232d61335d99391cc94430ac1295272f

**Comment by lsolesen** [comment]
Cool.
Den 27/08/2015 14.54 skrev "Matt Glaman" notifications@github.com:
