### ISSUE TITLE
Strange page on the outlet page

### ISSUE THREAD

**Issue by lsolesen** [discimport/discimport-build#25]
http://discimport.dk/products?f%5B0%5D=field_discount_group%3A196&f%5B1%5D=field_discount_group%3A195&f%5B2%5D=field_discount_group%3A194&f%5B3%5D=field_discount_group%3A192&f%5B4%5D=field_discount_group%3A193&f%5B5%5D=field_discount_group%3A190

Guessing that this is a CK problem?

**Comment by lsolesen** [comment]
See also: http://discimport.dk/products?search_api_views_fulltext=&page=1

**Comment by mglaman** [comment]
@lsolesen can you attach screenshot of exact issue
