### ISSUE TITLE
Add Commerce Giftcard

### ISSUE THREAD

**Issue by lsolesen** [discimport/discimport-build#26]
Add commerce_gc to discimport.dk for better giftcard handling. It should be so a user can buy a giftcard and give to someone. But it should also be so that we can give giftcards for tournaments etc.

**Comment by mglaman** [comment]
Needs some more testing, but linked to commits on branches which implement this. discimport-build has makefile additions, deploy has updates, and discount has exported node type. Seems to work all right out of the box so far.

**Comment by mglaman** [comment]
The biggest remaining item is "It should be so a user can buy a giftcard and give to someone"

**Comment by lsolesen** [comment]
@mglaman How close is this before it is ready for production?

**Comment by lsolesen** [comment]
What is the holdup for getting this to work. Do you have any questions?

**Comment by mglaman** [comment]
@lsolesen I just need to verify the email functionality.

**Comment by mglaman** [comment]
Ok, @lsolesen this should be set. It'll make product display for GC and use line item so they can send it to others.

**Comment by lsolesen** [comment]
Upgrading production now. Looking forward to see how this works :)

**Comment by lsolesen** [comment]
@mglaman Is this the expected product display? http://discimport.dk/giftcard/gavekort

**Comment by mglaman** [comment]
Yes.. except I don't know why it's showing empty variations. They enter email there and Rules creates them a user to hold the reference to the gift card

**Comment by lsolesen** [comment]
Empty variations is when there is only one variation. Seems to be an error
in the module.

**Comment by lsolesen** [comment]
@mglaman Maybe this needs an issue in the commerce_gc module and a patch?

**Comment by mglaman** [comment]
Looking into this

**Comment by mglaman** [comment]
The bug is the field display instance config, will update.
