### ISSUE TITLE
It is not obvious right now how to buy

### ISSUE THREAD

**Issue by lsolesen** [discimport/discimport-build#30]
Right now the page for buying is not so easy to understand. It seems that some work is not quite finished yet?

The add to cart stuff is there twice, e.g. http://discimport.dk/discgolf/tank-base

**Comment by mglaman** [comment]
It looks like the original add to cart was put back.. when you want only the table at the bottom, correct?

**Comment by lsolesen** [comment]
@mglaman Yeah. I want the table, so it is easier to see what is in stock.

**Comment by mglaman** [comment]
All instances should be fixed, and cart table bumped up above reviews so it looks inline.
