### ISSUE TITLE
It is not possible to use coupons

### ISSUE THREAD

**Issue by lsolesen** [discimport/discimport-build#31]
For some reason the new coupons is not working. @mglaman Could you please look at this pretty quick, as I have waiting customers, thanks.

**Comment by mglaman** [comment]
@lsolesen is the issue due to coupons not being part of a discount? You might have to manually edit a discount and add existing coupon codes to the matching discount.

**Comment by lsolesen** [comment]
I will retest. Before all of your work it was not possible to actually use
the coupons.

**Comment by mglaman** [comment]
@lsolesen wanted to circle back on this, see if Coupons are applying as they should.

**Comment by lsolesen** [comment]
I think they are now. Let's close this for now. I am doing BLACK-FRIDAY on friday, so it will show there :)
