### ISSUE TITLE
Create giftcard directly on a user

### ISSUE THREAD

**Issue by lsolesen** [discimport/discimport-build#32]
How do I create a giftcard directly on a user?

**Comment by mglaman** [comment]
You would visit: admin/commerce/coupons/add/giftcard-coupon. Make or generate a code and then select a user and fill out the rest of the values.
![screenshot from 2015-10-10 15 02 16](https://cloud.githubusercontent.com/assets/3698644/10413005/f614f30a-6f5f-11e5-84c0-dada835554e3.png)

Dev version has links fixed so this can be tested. In fact, this linked worked just fine before #27 was resolved.
