### ISSUE TITLE
stadig fejl ved manuel rabat-linje i ordre

### ISSUE THREAD

**Issue by mikaelbirkelundjohansen** [discimport/discimport-build#4]
Når man manuelt laver en rabat, så kan man ikke efterfølgende se den som en linje i ordren? den beregner, men man kan ikke se den og kan derfor ikke rette i den. 
Har stor behov for at få de rabatter jeg har sat på ordre 158 fjernet igen.

**Comment by lsolesen** [comment]
Der er ikke nogen rabatter at se lige nu, men hvad skal selve ordrens beløb være?

**Comment by mikaelbirkelundjohansen** [comment]
Jeg tror den slettede det da jeg skrev 0 i en ny rabatkupon. Jeg kiggger lige på det og vender tilbage

**Comment by lsolesen** [comment]
Status?
