### ISSUE TITLE
Product variation titles disappeared on a bunch of products

### ISSUE THREAD

**Issue by lsolesen** [discimport/discimport-build#43]
I have no idea why, but they all need to be rebuilt. Otherwise it is hard to use the shop properly and we are loosing sales.

@mglaman Can you fix this ASAP?

**Comment by mglaman** [comment]
The variations didn't get lost, just the references went missing?

**Comment by lsolesen** [comment]
A, just the product variation TITLES disappeared.

**Comment by lsolesen** [comment]
They are still missing on a bunch of products, like http://discimport.dk/node/285/edit. I just manually rebuilt a lot by visiting http://discimport.dk/admin/commerce/products/variations. Now when I sort by title noone is missing it's titles, but still there is a lot when I edit them. However, do I search for that product SKU under variations a title is set. Something strange is going on.

@mglaman Can you revisit?
