### ISSUE TITLE
hvordan ændrer jeg på beløbet ved en kort-betaling?

### ISSUE THREAD

**Issue by mikaelbirkelundjohansen** [discimport/discimport-build#5]
jeg har behov for at lave beløbet om på en visa-betaling. hvordan gør jeg det?

**Comment by lsolesen** [comment]
http://drupal.org/node/1843934

**Comment by lsolesen** [comment]
Tjek lige nu om du kan hæve det beløb, du har lyst til og skriv resultatet ind i dette issue.

**Comment by lsolesen** [comment]
This issue has been fixed by the current changes to quickpay drupal module.
